services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: BOOKING_APP_DB
      MYSQL_ROOT_PASSWORD: Alskdjfhg6!
      MYSQL_USER: USER_DB
      MYSQL_PASSWORD: Alskdjfhg6!
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
